# Generated by Django 5.1.5 on 2025-07-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_task_priority_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', '🔴 High Priority'), ('medium', '🟡 Medium Priority'), ('low', '⚪ Low Priority')], default='low', max_length=10),
        ),
    ]
