# Generated by Django 5.1.5 on 2025-07-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_task_due_date_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.AddField(
            model_name='task',
            name='due_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
